FROM --platform=linux/amd64 ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get -yq dist-upgrade
RUN apt-get update
RUN apt-get -yq dist-upgrade
RUN apt-get install -yq --no-install-recommends apt-utils build-essential bzip2 ca-certificates cmake coreutils curl emacs  emacs nano vim fonts-liberation gettext gfortran git git-all git-flow git-lfs gnupg gpg gpg-agent gzip hdf5-tools libcurl4-openssl-dev libgconf-2-4 libgtk2.0-0 libnss3 libpgf-dev libpgf6 libpgf6-dbg libpng-dev libssl-dev libxss1 libxtst6 locales lsb-release m4 nano openssh-client openssl pdf2svg poppler-utils screen sudo tmux  tree unzip vim wget xdg-utils zip zlib1g-dev
RUN apt-get update
RUN apt-get -yq dist-upgrade
RUN apt-get update
RUN apt-get -yq dist-upgrade
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen
ENV SHELL=/bin/bash
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV PROMPT_COMMAND="echo -n [$()]"
RUN mkdir -p /tmp/simplecontainergenerator_containers-julia-gpg-key
RUN cd /tmp/simplecontainergenerator_containers-julia-gpg-key && curl https://julialang.org/assets/juliareleases.asc --output juliareleases.asc
RUN cd /tmp/simplecontainergenerator_containers-julia-gpg-key && gpg --import juliareleases.asc
RUN rm -rf /tmp/simplecontainergenerator_containers-julia-gpg-key
RUN mkdir -p /tmp/simplecontainergenerator_containers-download-julia
RUN cd /tmp/simplecontainergenerator_containers-download-julia && wget -O julia.tar.gz https://julialang-s3.julialang.org/bin/linux/x64/1.10/julia-1.10.2-linux-x86_64.tar.gz
RUN cd /tmp/simplecontainergenerator_containers-download-julia && wget -O julia.tar.gz.asc https://julialang-s3.julialang.org/bin/linux/x64/1.10/julia-1.10.2-linux-x86_64.tar.gz.asc
RUN cd /tmp/simplecontainergenerator_containers-download-julia && gpg --verify julia.tar.gz.asc
RUN mkdir -p /opt
RUN cd /tmp/simplecontainergenerator_containers-download-julia && tar xzf julia.tar.gz -C /opt --strip-components=1
RUN rm -rf /tmp/simplecontainergenerator_containers-download-julia
RUN rm -rf /tmp/simplecontainergenerator-containers-build-depot
RUN mkdir -p /tmp/simplecontainergenerator-containers-build-depot
RUN cd /tmp; JULIA_DEPOT_PATH=/tmp/simplecontainergenerator-containers-build-depot /opt/bin/julia -e 'import InteractiveUtils; InteractiveUtils.versioninfo(; verbose=true)'
RUN rm -rf /tmp/simplecontainergenerator-containers-build-depot
RUN rm -rf /opt/etc/julia/startup.jl
RUN rm -rf /opt/share/julia/compiled
RUN rm -rf /usr/bin/julia
RUN mkdir -p /opt/etc/julia
RUN mkdir -p /opt/simplecontainergenerator_containers
RUN mkdir -p /opt/simplecontainergenerator_containers/backup_of_dockerfile
RUN mkdir -p /opt/simplecontainergenerator_containers/depot_backup_simplecontainergenerator
RUN mkdir -p /opt/simplecontainergenerator_containers/depot_backup_packagecompiler
RUN mkdir -p /opt/simplecontainergenerator_containers/packagecompiler_depot
RUN mkdir -p /opt/simplecontainergenerator_containers/julia_depot
RUN mkdir -p /opt/simplecontainergenerator_containers/julia_project
RUN mkdir -p /opt/simplecontainergenerator_containers/sysimage
RUN mkdir -p /usr/bin
RUN mkdir -p /tmp/staging/copyfiles/opt/simplecontainergenerator_containers
COPY simplecontainergenerator_container_files/file_1/backups_of_simplecontainergenerator_1.jl /tmp/staging/copyfiles/opt/simplecontainergenerator_containers/backups_of_simplecontainergenerator_1.jl
RUN mkdir -p /tmp/staging/copyfiles/opt/simplecontainergenerator_containers
COPY simplecontainergenerator_container_files/file_2/backups_of_simplecontainergenerator_2.jl /tmp/staging/copyfiles/opt/simplecontainergenerator_containers/backups_of_simplecontainergenerator_2.jl
RUN mkdir -p /tmp/staging/copyfiles/opt/simplecontainergenerator_containers
COPY simplecontainergenerator_container_files/file_3/install_packages.jl /tmp/staging/copyfiles/opt/simplecontainergenerator_containers/install_packages.jl
RUN mkdir -p /tmp/staging/copyfiles/usr/bin
COPY simplecontainergenerator_container_files/file_4/julia /tmp/staging/copyfiles/usr/bin/julia
RUN mkdir -p /tmp/staging/copyfiles/usr/bin
COPY simplecontainergenerator_container_files/file_5/no_sysimage_julia /tmp/staging/copyfiles/usr/bin/no_sysimage_julia
RUN mkdir -p /tmp/staging/copyfiles/opt/simplecontainergenerator_containers
COPY simplecontainergenerator_container_files/file_6/packagecompiler_install.jl /tmp/staging/copyfiles/opt/simplecontainergenerator_containers/packagecompiler_install.jl
RUN mkdir -p /tmp/staging/copyfiles/opt/simplecontainergenerator_containers
COPY simplecontainergenerator_container_files/file_7/packagecompiler_run.jl /tmp/staging/copyfiles/opt/simplecontainergenerator_containers/packagecompiler_run.jl
RUN mkdir -p /tmp/staging/copyfiles/opt/simplecontainergenerator_containers
COPY simplecontainergenerator_container_files/file_8/precompile_execution.jl /tmp/staging/copyfiles/opt/simplecontainergenerator_containers/precompile_execution.jl
RUN mkdir -p /tmp/staging/copyfiles/opt/etc/julia
COPY simplecontainergenerator_container_files/file_9/startup.jl /tmp/staging/copyfiles/opt/etc/julia/startup.jl
RUN rm -rf /opt/simplecontainergenerator_containers/backups_of_simplecontainergenerator_1.jl
RUN rm -rf /opt/simplecontainergenerator_containers/backups_of_simplecontainergenerator_2.jl
RUN rm -rf /opt/simplecontainergenerator_containers/install_packages.jl
RUN rm -rf /usr/bin/julia
RUN rm -rf /usr/bin/no_sysimage_julia
RUN rm -rf /opt/simplecontainergenerator_containers/packagecompiler_install.jl
RUN rm -rf /opt/simplecontainergenerator_containers/packagecompiler_run.jl
RUN rm -rf /opt/simplecontainergenerator_containers/precompile_execution.jl
RUN rm -rf /opt/etc/julia/startup.jl
RUN mkdir -p /opt/simplecontainergenerator_containers
RUN mkdir -p /usr/bin
RUN mkdir -p /opt/etc/julia
RUN cp /tmp/staging/copyfiles/opt/simplecontainergenerator_containers/backups_of_simplecontainergenerator_1.jl /opt/simplecontainergenerator_containers/backups_of_simplecontainergenerator_1.jl
RUN cp /tmp/staging/copyfiles/opt/simplecontainergenerator_containers/backups_of_simplecontainergenerator_2.jl /opt/simplecontainergenerator_containers/backups_of_simplecontainergenerator_2.jl
RUN cp /tmp/staging/copyfiles/opt/simplecontainergenerator_containers/install_packages.jl /opt/simplecontainergenerator_containers/install_packages.jl
RUN cp /tmp/staging/copyfiles/usr/bin/julia /usr/bin/julia
RUN cp /tmp/staging/copyfiles/usr/bin/no_sysimage_julia /usr/bin/no_sysimage_julia
RUN cp /tmp/staging/copyfiles/opt/simplecontainergenerator_containers/packagecompiler_install.jl /opt/simplecontainergenerator_containers/packagecompiler_install.jl
RUN cp /tmp/staging/copyfiles/opt/simplecontainergenerator_containers/packagecompiler_run.jl /opt/simplecontainergenerator_containers/packagecompiler_run.jl
RUN cp /tmp/staging/copyfiles/opt/simplecontainergenerator_containers/precompile_execution.jl /opt/simplecontainergenerator_containers/precompile_execution.jl
RUN cp /tmp/staging/copyfiles/opt/etc/julia/startup.jl /opt/etc/julia/startup.jl
RUN rm -rf /tmp/staging
RUN chmod 444 /opt/etc/julia/startup.jl
RUN chmod 555 /usr/bin/julia
RUN chmod 555 /usr/bin/no_sysimage_julia
RUN cd /tmp; JULIA_DEBUG=all SIMPLECONTAINERGENERATOR_CONTAINER_NO_TEMP_DEPOT="true" /usr/bin/no_sysimage_julia /opt/simplecontainergenerator_containers/install_packages.jl
RUN cd /tmp; JULIA_DEBUG=all /opt/bin/julia /opt/simplecontainergenerator_containers/backups_of_simplecontainergenerator_1.jl
RUN cd /tmp; JULIA_DEBUG=all /opt/bin/julia /opt/simplecontainergenerator_containers/backups_of_simplecontainergenerator_2.jl
RUN cd /tmp; JULIA_DEBUG=all /opt/bin/julia /opt/simplecontainergenerator_containers/packagecompiler_install.jl
RUN cd /tmp; SIMPLECONTAINERGENERATOR_CONTAINER_NO_TEMP_DEPOT="true" /usr/bin/no_sysimage_julia /opt/simplecontainergenerator_containers/packagecompiler_run.jl
RUN cd /tmp; JULIA_DEBUG=all /usr/bin/no_sysimage_julia -e 'import InteractiveUtils; InteractiveUtils.versioninfo(; verbose=true)'
RUN cd /tmp; JULIA_DEBUG=all /usr/bin/julia -e 'import InteractiveUtils; InteractiveUtils.versioninfo(; verbose=true)'
RUN rm -rf /opt/bin/julia/compiled
RUN rm -rf /opt/etc/julia/compiled
RUN rm -rf /opt/share/julia/compiled
RUN rm -rf /opt/simplecontainergenerator_containers/depot_backup_simplecontainergenerator/compiled
RUN rm -rf /opt/simplecontainergenerator_containers/depot_backup_packagecompiler/compiled
RUN rm -rf /opt/simplecontainergenerator_containers/packagecompiler_depot/compiled
RUN rm -rf /opt/simplecontainergenerator_containers/julia_depot/compiled
RUN rm -rf /opt/simplecontainergenerator_containers/julia_project/compiled
RUN rm -rf /opt/simplecontainergenerator_containers/sysimage/compiled
RUN find /opt -type d -print0 | xargs -0 chmod a+rx
RUN find /opt -type f -print0 | xargs -0 chmod a+r
RUN chmod a+rx /opt/bin/julia
RUN chmod a+rx /usr/bin/julia
RUN chmod a+rx /usr/bin/no_sysimage_julia
RUN mkdir -p /opt/simplecontainergenerator_containers/backup_of_dockerfile
COPY Dockerfile /opt/simplecontainergenerator_containers/backup_of_dockerfile/Dockerfile
ENTRYPOINT ["/bin/bash", "-c"]

