apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: automl-dualsearch
spec:
  entrypoint: run-main
  arguments:
    parameters:
      - name: input
        value: iris_reg.csv
      - name: predictiontype
        value: regression
      - name: folds
        value: 3
      - name: workers
        value: 5
  templates:
    - name: run-main
      inputs:
        parameters:
          - name: input
          - name: predictiontype
          - name: folds
          - name: workers
      steps:
        - - name: low-complexity
            template: run-amlp
            arguments:
              parameters:
                - name: complexity
                  value: low
                - name: input
                  value: "{{inputs.parameters.input}}"
                - name: predictiontype
                  value: "{{inputs.parameters.predictiontype}}"
                - name: folds
                  value: "{{inputs.parameters.folds}}"
                - name: workers
                  value: "{{inputs.parameters.workers}}"

          - name: high-complexity
            template: run-amlp
            arguments:
              parameters:
                - name: complexity
                  value: high
                - name: input
                  value: "{{inputs.parameters.input}}"
                - name: predictiontype
                  value: "{{inputs.parameters.predictiontype}}"
                - name: folds
                  value: "{{inputs.parameters.folds}}"
                - name: workers
                  value: "{{inputs.parameters.workers}}"

    - name: run-amlp
      inputs:
        parameters:
          - name: complexity
          - name: input
          - name: predictiontype
          - name: folds
          - name: workers
        artifacts:
          - name: file
            path: /inputfile
            s3:
              key: csv/
      container:
        image: ppalmes/automlpipeline:latest
        command:
        args:
          - "-t{{inputs.parameters.predictiontype}}"
          - "-c{{inputs.parameters.complexity}}"
          - "-f{{inputs.parameters.folds}}"
          - "-w{{inputs.parameters.workers}}"
          - "-o/outputfile"
          - "/inputfile/{{inputs.parameters.input}}"
      outputs:
        artifacts:
          - name: ofile
            path: /outputfile
            s3:
              key: "output/{{inputs.parameters.complexity}}_{{inputs.parameters.predictiontype}}_{{inputs.parameters.input}}.tgz"
