apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: automlai-prediction
spec:
  entrypoint: run-amlp
  arguments:
    parameters:
      - name: url
        value: http://sunrise-mlflow-tracking.mlflow:5080
      - name: input
        value: iris_reg.csv
      - name: predictiontype
        value: regression
      - name: outputloc
        value: output.txt
      - name: runid
        value: NONE
  templates:
    - name: run-amlp
      inputs:
        parameters:
          - name: url
          - name: input
          - name: predictiontype
          - name: outputloc
          - name: runid
        artifacts:
          - name: file
            path: /inputfile
            s3:
              key: csv/
      container:
        image: ppalmes/automlai:v2.0
        command:
        args:
          - "-u{{inputs.parameters.url}}"
          - "-t{{inputs.parameters.predictiontype}}"
          - "-o/outputfile"
          - "--predict_only"
          - "--runid {{inputs.parameters.runid}}"
          - "/inputfile/{{inputs.parameters.input}}"
      outputs:
        artifacts:
          - name: ofile
            path: /outputfile
            s3:
              key: "output/{{inputs.parameters.predictiontype}}_{{inputs.parameters.input}}.tgz"
